version: '3'
services:
  app-nginx:
    image: nginx:latest
    restart: always
    container_name: app-nginx
    volumes:
      - ./images/nginx:/etc/nginx/conf.d
      - ../app:/var/www/app
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app-php
      - app-mysql
    ports:
      - "86:80"
    networks:
      - net

  app-php:
    build: ./images/php
    restart: always
    container_name: app-php
    environment:
      APP_DEBUG: 1
    depends_on:
      - app-mysql
    volumes:
      - ../app:/var/www/app
      - ./images/php/custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    networks:
      - net

  app-mysql:
    image: mysql:5.7.36
    container_name: app-mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: b13766_hermanos
    volumes:
      - ./data/data:/var/lib/mysql
      - ./images/mysql/my.cnf:/etc/mysql/my.cnf
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - net

networks:
  net: